/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-container-highest": "#e0e3e5",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#00174b",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "tertiary-fixed-dim": "#ffb596",
        "surface-container-low": "#f2f4f6",
        "on-secondary-fixed-variant": "#31447b",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#dbe1ff",
        "outline-variant": "#c3c6d7",
        "on-background": "#191c1e",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-dim": "#d8dadc",
        "background": "#f7f9fb",
        "outline": "#737686",
        "surface-variant": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-container": "#394c84",
        "on-surface-variant": "#434655",
        "secondary": "#495c95",
        "on-primary-fixed": "#00174b",
        "surface": "#f7f9fb",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed-dim": "#b4c5ff",
        "on-primary-container": "#eeefff",
        "inverse-primary": "#b4c5ff",
        "inverse-surface": "#2d3133",
        "tertiary": "#943700",
        "surface-tint": "#0053db",
        "tertiary-container": "#bc4800",
        "primary": "#004ac6",
        "tertiary-fixed": "#ffdbcd",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed": "#dbe1ff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#360f00",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-container": "#2563eb",
        "secondary-container": "#acbfff",
        "on-tertiary-container": "#ffede6",
        "on-surface": "#191c1e"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
